FROM node:lts-alpine

ENV REACT_APP_BACKEND_URL=http://localhost:8080/

COPY . .

WORKDIR /example-frontend

RUN npm install
RUN npm run build
RUN npm install -g serve

EXPOSE 5000

CMD serve -s -l 5000 build