#RUN in: material-applications-main\example-frontend

#Use nodeJS
FROM node:16  

#Use port 5000
EXPOSE 5000

#Use ENV to connect to backend port
ENV REACT_APP_BACKEND_URL http://localhost:8080

#Use /usr/src/app as our workdir.
WORKDIR /usr/src/myapp

#Copy package, will not work otherwise
COPY package*.json ./  

#Copy the src and json
COPY . .

#NPM operations
RUN npm install 
RUN npm list 
RUN npm run build
RUN npm install -g serve  

#Command to run the application
CMD ["serve", "-s", "-l", "5000", "build"]