FROM golang:1.16

WORKDIR /usr/src/app

EXPOSE 8080

COPY . .

RUN go build
ENV REQUEST_ORIGIN=http://localhost

#Setting non-root user
RUN useradd -m appuser
RUN chown appuser .
USER appuser

CMD ./server