const App = (props) => {
  const { notes } = props

  return (
    <div>
      <h1>Notes</h1>
      {/*using map fx to render notes */}
      <ul>
        {notes.map(note => 
          /* Elements generated by map methods require unique ket value*/
          <li key={note.id}>
            {note.content}
          </li>
        )}
      </ul>
    </div>
  )
}