import Note from "./Note"

const App = ({ notes }) => {
  return (
    <div>
      <h1>Notes</h1>
      {/*using map fx to render notes */}
      <ul>

        {notes.map(note => 
        /* Elements generated by map methods require unique ket value*/
          <Note key={note.id} note={note} />
        )}
      </ul>
    </div>
  )
}

export default App
