version: "3.8"

services:
    backend:
        container_name: backend
        image: backend
        build: ./backend
        ports:
            - 8080:8080
        environment:
            REDIS_HOST: redis
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
            REQUEST_ORIGIN: http://localhost:80
        depends_on:
            - redis
            - postgres
        networks:
            - app-network

    frontend:
        container_name: frontend
        image: frontend
        build: ./frontend
        ports:
            - 5000:5000
        environment:
            REACT_APP_BACKEND_URL: http://localhost:80
        networks:
            - app-network

    redis:
        image: redis
        container_name: redis-cache
        restart: unless-stopped
        networks:
            - app-network

    postgres:
        image: postgres
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        networks:
            - app-network

    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
