FROM ubuntu:22.10

WORKDIR /usr/src/app

COPY . . 

EXPOSE 5000

# Update ubuntu and install needed software
RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash
RUN apt install -y nodejs

RUN npm install 
RUN npm install -g serve 

ENV REACT_APP_BACKEND_URL=http://localhost:8080
RUN npm run build 

#Setting non-root user
RUN useradd -m appuser
RUN chown appuser .

USER appuser

CMD [ "serve", "-s", "-l", "5000", "build" ]