#This yml file assumes that the dockerfiles in excercise 1.12 and 1.13 have been built and are being used
version: "3.8"

services:
    backend: 
        image: backend
        build: ./backend
        ports: 
            - 8080:8080
        container_name: backend
    frontend:
        image: frontend
        build: ./frontend
        ports:
            - 5000:5000
        container_name: frontend